### ISSUE TITLE
IA não considera que o player joga antes dela

### ISSUE THREAD

**Issue by gustavo-goncalves** [GFiuza/Connect4-Minimax#2]
|___|___|___|___|___|___|___|
|___|___|___|___|___|___|___|
|_X_|___|___|___|___|___|___|
|_O_|_O_|_X_|___|___|___|___|                                               ### Vez do jogador 1 ### Sua vez: >? 5
|_O_|_O_|_X_|___|___|___|___|
|_O_|_X_|_O_|_X_|_X_|___|___|
  0   1   2   3   4   5   6

|___|___|___|___|___|___|___|
|___|___|___|___|___|___|___|
|_X_|_O_|___|___|___|___|___|
|_O_|_O_|_X_|___|___|___|___|                                             ### Vez do jogador 1 ### Sua vez: >? 6
|_O_|_O_|_X_|___|___|___|___|
|_O_|_X_|_O_|_X_|_X_|_X_|___|
  0   1   2   3   4   5   6

|_O_|_O_|_O_|_O_|_O_|_O_|_O_|
|_O_|_O_|_O_|_O_|_O_|_O_|_O_|
|_O_|_O_|_O_|_O_|_O_|_O_|_O_|
|_O_|_O_|_O_|_O_|_O_|_O_|_O_|
|_O_|_O_|_O_|_O_|_O_|_O_|_O_|
|_O_|_O_|_O_|_O_|_O_|_O_|_O_|
  0   1   2   3   4   5   6
!!! JOGADOR 2 VENCEU !!!

**Comment by GFiuza** [comment]
O problema era a função de avaliação, era um erro bobo.
